remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Thông tin cá nhân - Chú ý dấu cách sau dấu hai chấm
title: "Portfolio của Lê Văn Hoàng"
name: "Lê Văn Hoàng"
description: "Sinh viên ngành IoT - Học viện Công nghệ Bưu chính Viễn thông"
bio: "IoT Student"
location: "Ho Chi Minh City, Vietnam"
email: "hoanghoang301205@gmail.com"
github: "hoanghoang301205-max"
url: "https://hoanghoang301205-max.github.io"
avatar: "/assets/img/avt.jpg"

# Cấu hình mặc định
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
