title: Portfolio của Lê Văn Hoàng
name: Lê Văn Hoàng
description: Sinh viên ngành IoT - PTIT
bio: IoT Student
location: Ho Chi Minh City, Vietnam
email: hoanghoang301205@gmail.com
github: hoanghoang301205-max
url: "https://hoanghoang301205-max.github.io"
avatar: "https://hoanghoang301205-max.github.io/avt.jpg"
